baseURL = "http://example.org/"
languageCode = "es-es"
title = "JuancPulidos "
theme = "ghostwriter"
copyright = "juancpulidos"

[Author]
    name = "Juan Carlos Pulido S."
    profile = "https://google.com/+XXX"

[Params]
    intro = true
    headline = "Desarrollo Web"
    description = "16 a침os de experiencia como desarrollador web y dise침ador UI. Me gusta aprender constantemente y quiero compartir mis conocimientos contigo. Esta p치gina web es un excelente recurso para que adquieras conocimientos en programaci칩n."
    github = "https://github.com/alephart"
    linkedin = "https://linkedin.com/in/juancpulidos/"
    gplus = "https://google.com/+XXX"
    twitter = "https://twitter.com/juancpulidosme"
    stackoverflow = "https://stackoverflow.com/users/1842574/juan-carlos-pulido-suarez"
    email = "hola@juancpulidos.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false
    readingTime = true
    readingTimeText = "Tiempo estimado de lectura:"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Proyectos"
    url = "/project/"
    weight = 3

[[menu.main]]
    name = "Contacto"
    url = "/page/contact/"
    weight = 4

[[menu.main]]
    name = "Acerca de mi"
    url = "/page/about/"
    weight = 2